# Generated by Django 3.2.8 on 2021-10-26 15:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ChatMessages',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sender', models.CharField(max_length=60)),
                ('room_name', models.CharField(max_length=60)),
                ('message', models.TextField()),
                ('timestamp', models.TimeField()),
            ],
        ),
    ]
