# Generated by Django 3.2.8 on 2021-10-26 16:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chatmessages',
            name='timestamp',
            field=models.DateTimeField(),
        ),
    ]
